import js from '@eslint/js';

const browserGlobals = Object.fromEntries([
  'AbortController',
  'Blob',
  'CSS',
  'CustomEvent',
  'DOMException',
  'Element',
  'Event',
  'File',
  'FormData',
  'HTMLButtonElement',
  'HTMLInputElement',
  'HTMLElement',
  'HTMLSelectElement',
  'HTMLTextAreaElement',
  'Image',
  'KeyboardEvent',
  'MutationObserver',
  'Node',
  'TextDecoder',
  'TextEncoder',
  'URL',
  'URLSearchParams',
  'addEventListener',
  'cancelAnimationFrame',
  'clearInterval',
  'clearTimeout',
  'console',
  'crypto',
  'document',
  'fetch',
  'getComputedStyle',
  'history',
  'localStorage',
  'location',
  'matchMedia',
  'navigator',
  'performance',
  'queueMicrotask',
  'requestAnimationFrame',
  'setInterval',
  'setTimeout',
  'sessionStorage',
  'structuredClone',
  'window',
].map((name) => [name, 'readonly']));

const nodeGlobals = Object.fromEntries([
  'AbortController',
  'Blob',
  'Buffer',
  'DOMException',
  'File',
  'FormData',
  'TextDecoder',
  'TextEncoder',
  'URL',
  'URLSearchParams',
  '__dirname',
  '__filename',
  'clearImmediate',
  'clearInterval',
  'clearTimeout',
  'console',
  'exports',
  'fetch',
  'global',
  'module',
  'process',
  'queueMicrotask',
  'Request',
  'require',
  'setImmediate',
  'setInterval',
  'setTimeout',
  'structuredClone',
].map((name) => [name, 'readonly']));

export default [
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.js', 'public/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: browserGlobals,
    },
  },
  {
    files: ['tests/**/*.{js,mjs}', 'scripts/**/*.{js,mjs}', 'vite.config.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...nodeGlobals, ...browserGlobals },
    },
  },
];
