/** Each entry has its own rules and renderer. No numbered variants. */
/** @type {import("../types.js").Game[]} */
export const SOLO_GAMES = [
  { id: 'apex-circuit', title: 'Apex Circuit', category: 'Arcade', engine: 'driving', icon: '↗', accent: 'green', blurb: 'Find your racing line. Three laps, two AI rivals, one real-time 3D circuit.', options: { dimension: '3D', launch: '/drive.html', cover: 'apex-circuit', label: 'Circuit racing' } },
  { id: 'neon-snake', title: 'Neon Snake', category: 'Arcade', engine: 'snake', icon: '⌁', accent: 'green', blurb: 'Chase the next bite. Grow longer, turn tighter, and never cross your own tail.', options: { dimension: '2D', launch: '/play.html?game=neon-snake', cover: 'neon-snake', label: 'Survival' } },
  { id: 'prism-breaker', title: 'Prism Breaker', category: 'Arcade', engine: 'breakout', icon: '▰', accent: 'violet', blurb: 'Aim your rebounds. Clear three brick formations before your last ball drops.', options: { dimension: '2D', launch: '/play.html?game=prism-breaker', cover: 'prism-breaker', label: 'Brick breaker' } },
  { id: 'star-defender', title: 'Star Defender', category: 'Arcade', engine: 'shooter', icon: '✧', accent: 'orange', blurb: 'Dodge enemy fire and break the formation. Three waves stand between you and victory.', options: { dimension: '2D', launch: '/play.html?game=star-defender', cover: 'star-defender', label: 'Space shooter' } },
  { id: 'merge-2048', title: 'Merge 2048', category: 'Puzzle', engine: 'merge', icon: '▦', accent: 'orange', blurb: 'Slide equal tiles together. Build the golden 2048 tile before the board fills.', options: { dimension: '2D', launch: '/collection.html?game=merge-2048', cover: 'merge-2048', label: 'Sliding number puzzle' } },
  { id: 'minefield', title: 'Minefield', category: 'Puzzle', engine: 'mines', icon: '⚑', accent: 'cyan', blurb: 'Read the clues, mark the danger, and uncover every safe square. Your first reveal is safe.', options: { dimension: '2D', launch: '/collection.html?game=minefield', cover: 'minefield', label: 'Minesweeper' } },
  { id: 'reversi', title: 'Reversi', category: 'Strategy', engine: 'reversi', icon: '◐', accent: 'green', blurb: 'Outflank your opponent and turn the board. Play the CPU or a friend on this device.', options: { dimension: '2D', launch: '/collection.html?game=reversi', cover: 'reversi', label: 'Disc-flipping strategy', players: 'Solo / local 2P' } },
  { id: 'pocket-golf', title: 'Pocket Golf', category: 'Arcade', engine: 'golf', icon: '⚑', accent: 'green', blurb: 'Aim your shot, judge the power, and bank around obstacles across three little greens.', options: { dimension: '2D', launch: '/collection.html?game=pocket-golf', cover: 'pocket-golf', label: 'Physics golf' } },
  { id: 'falling-blocks', title: 'Falling Blocks', category: 'Arcade', engine: 'blocks', icon: '▣', accent: 'violet', blurb: 'Rotate, stack, and clear twenty lines. Seven different pieces, one rising challenge.', options: { dimension: '2D', launch: '/challenge.html?game=falling-blocks', cover: 'falling-blocks', label: 'Falling-block puzzle' } },
  { id: 'crate-shift', title: 'Crate Shift', category: 'Puzzle', engine: 'sokoban', icon: '▧', accent: 'orange', blurb: 'Push every crate onto its target. Plan ahead, undo a mistake, and solve four warehouse rooms.', options: { dimension: '2D', launch: '/challenge.html?game=crate-shift', cover: 'crate-shift', label: 'Sokoban' } },
  { id: 'orbit-lander', title: 'Orbit Lander', category: 'Arcade', engine: 'lander', icon: '↧', accent: 'cyan', blurb: 'Balance thrust, gravity and limited fuel. A gentle touchdown is the only way home.', options: { dimension: '2D', launch: '/challenge.html?game=orbit-lander', cover: 'orbit-lander', label: 'Lunar flight physics' } },
  { id: 'hex-flood', title: 'Hex Flood', category: 'Puzzle', engine: 'flood', icon: '⬡', accent: 'pink', blurb: 'Choose a colour and grow your territory. Capture all 81 hexes before thirty moves run out.', options: { dimension: '2D', launch: '/challenge.html?game=hex-flood', cover: 'hex-flood', label: 'Colour territory puzzle' } },
];
